<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CommunityCricketPage"
           tests="4"
           failures="1"
           errors="0"
           skipped="0"
           time="295.758">
  <properties />
            <testcase name="verifyCoachCricket" time="23.466" classname="com.ca.CommunityCricketPageTestcases.GetInvolvedTestcases">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [https://community.cricket.com.au/coach] but found [https://www.community.cricket.com.au/coach]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [https://community.cricket.com.au/coach] but found [https://www.community.cricket.com.au/coach]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
  com.CA.CommunityCricketPage.GetInvolved.CoachCricket(GetInvolved.java:247)
  com.ca.CommunityCricketPageTestcases.GetInvolvedTestcases.verifyCoachCricket(GetInvolvedTestcases.java:42)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:567)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:794)
  org.testng.TestRunner.run(TestRunner.java:596)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
  org.testng.SuiteRunner.run(SuiteRunner.java:276)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
  org.testng.TestNG.runSuites(TestNG.java:1063)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="verifyGetInvolved" time="12.091" classname="com.ca.CommunityCricketPageTestcases.GetInvolvedTestcases" />
                <testcase name="verifyUmpireandScoreCricket" time="115.105" classname="com.ca.CommunityCricketPageTestcases.GetInvolvedTestcases" />
                <testcase name="verifyPlayCricket" time="145.096" classname="com.ca.CommunityCricketPageTestcases.GetInvolvedTestcases" />
      
</testsuite>
